spring:
  application:
    name: split-together
  datasource:
    url: jdbc:postgresql://localhost:5432/splittogether
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

app:
  jwt:
    # TODO: load secret from environment variable before going to production
    secret: "tempMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI"
    access-token-expiry: 900000      # 15 minutes in ms
    refresh-token-expiry-days: 30

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
